- name: Install NFS
  hosts: nfs
  gather_facts: false
  become: true
  tasks:
    - name: Ensure NFS utilities are installed.
      apt:
        name:
          - nfs-common
          - nfs-kernel-server
        state: present
